version: '3.9'

services:
  tex:
    image: my-texlive:latest
    build:
      context: .
    volumes:
      - .:/workdir
    working_dir: /workdir
    command: sh -c 'latexmk -C main.tex && latexmk -shell-escape main.tex && latexmk -c main.tex && pdfunite title-page.pdf main.pdf so20_tanaka.pdf'
  sub:
    image: my-texlive:latest
    build:
      context: .
    volumes:
      - .:/workdir
    working_dir: /workdir
    command: sh -c 'latexmk -C sub.tex && latexmk -shell-escape sub.tex && latexmk -c sub.tex'